name: Build with .NET

on: [push]

jobs:
  build:

    strategy:
      matrix:
        include:
          - build-name: 'Windows'
            rid: win-x64
            platform: windows-latest
          - build-name: 'macOS'
            rid: osx-arm64
            platform: macos-latest
          - build-name: 'Linux'
            rid: linux-x64
            platform: ubuntu-latest

    name: ${{ matrix.build-name }}

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - name: Build Kamek for ${{ matrix.build-name }}
      shell: bash
      run: ./build_release.sh ${{ matrix.rid }}
    - uses: actions/upload-artifact@v4
      with:
        name: Kamek-${{ matrix.rid }}
        path: ${{ github.workspace }}/release
